### PR TITLE
Add integration with Foofle to quickly open search with element

### PR DESCRIPTION
**Pull request by Zomis**
To try it out, install this mod: https://mods.factorio.com/mod/foofle

Then open the game, press Ctrl + Shift + S and select an area, then click on something and then click the "Factory Search"-button.

Personally I think it makes it so much easier to search the factory, as you don't necessarily have to type in the element yourself in the search box. I hope you like it too.

### CODE REVIEW

**Comment by tburrows13** [comment]
Thanks for the contribution, I'll certainly have a look. But worth noting that you can already Control+Shift+Click on anything (entity, recipe, item, etc) to open the search for it. I haven't tried Foofle yet so I can't compare it, but I suspect that it _may_ have some overlap there. Having a common hotkey for lots of mods has some use though, since it saves you having to remember the click modifier for each individual mod.

**Comment by tburrows13** [comment]
Hey, I had a try with it. The integration looks fine, and I'm happy to merge it, although it seems to me that everything except the `"search"` remote interface could be done just as well on foofle's side (which means that you can maintain it in the future exactly how you like rather than relying on me merging PRs and releasing updates).

In terms of general feedback for foofle: it is clever and I can see the potential in the future, especially as more mods are supported. However, at least in its current state, I don't think it is there yet, so I don't think I'd want to 'advertise' it as a visible (optional) dependency.
A few specific issues:
- It seems to only work for items and fluids, and only when they are contents of chests, pipes, and storage tanks, even though it will let you select _any_ entity. It doesn't even work with the contents of logistic chests.
- You advertise on the mod portal "Ctrl + Shift and click", but that doesn't seem to be in the mod (and if it was it would conflict with the Factory Search keybind
- The Foofle GUI doesn't close when you press E. To fix this, set `player.opened` to your frame, and close your GUI wheno the `on_gui_closed` event is raised.
- The foofle select item can be placed into inventories (and is automatically returned to the inventory when your press Q). To avoid this, give the item prototype the "only-in-cursor" flag.

And more generally, I'm still struggling to see when this functionality would actually be useful...

**Comment by Zomis** [comment]
Hey. Thanks for your feedback. I will fix your suggestions and also record a video to showcase what the use-case for Foofle really is. (I think it's better explained in video format).

I have been using it while playing for a bit now and in my opinion it does make it faster to look at the same item/fluid in different mods.

I have not yet noticed that your Factory Search opens on Ctrl + Shift + click, but I will investigate further.

**Comment by Zomis** [comment]
It's true that Foofle could do all the integrations as long as there is a remote interface available. My reasoning was that other mods could be responsible for how they would want to show their buttons in Foofle. In the future I'm also planning for more GUI integrations that could be supported, in which case it would make sense to let the various mods be responsible for that, but perhaps that's more of a vision for later.

As for what Foofle supports in the selection: Some more things have been added in version 0.1.2. (No logistic chests yet though, I just forgot about those as I haven't been using them myself recently, I will add that support shortly)

I thought that the optional dependency was required in order to make it work with the remote interface, but it turns out that that's not the case so I am okay with leaving the optional dependency as.... optional.

---

I figured out what you mean by Ctrl + Shift + Click in Factory Search. It seems like Factory Search and Foofle is supporting two different kinds of Ctrl + Shift + Click. You support some things, while Foofle supports some others.

Here's a demo video that showcases the differences between the Foofle integrations and Factory Search, and the use-case for Foofle: https://www.youtube.com/watch?v=TkDi-X2bxJA&ab_channel=SimonForsberg (watching the first two minutes or so is probably enough in case you don't want to watch all 4.5 minutes)

**Comment by tburrows13** [comment]
> I thought that the optional dependency was required in order to make it work with the remote interface, but it turns out that that's not the case so I am okay with leaving the optional dependency as.... optional.

No, having a dependency is a good idea to ensure load order is consistent. I was just saying that it would probably be a hidden optional dependency (`(?) foofle`) which doesn’t show up in the dependencies list.

**Pull request closed without merging**
